r"""Tauri sidecar entry point.

Owns the per-launch lifecycle: pick a free TCP port on the loopback,
generate a 32-byte session token, build the FastAPI app, print the
handshake line on stdout (consumed by the Tauri shell to discover
``(port, token)``), then run uvicorn until SIGTERM / SIGINT.

Security guarantees (cf. ADR-0016):

* Bind address is hard-coded to ``127.0.0.1`` via
  :class:`guardiabox.config.SidecarSettings.host` typed as
  ``Literal["127.0.0.1"]`` -- env-var override is impossible.
* Session token is generated by :func:`secrets.token_urlsafe(32)`,
  giving 256 bits of entropy from the OS CSPRNG.
* Token is printed exactly once on stdout *before* uvicorn binds, so
  the Tauri shell sees it on the first newline of the child's stdout
  stream.
* The handshake format is fixed: ``GUARDIABOX_SIDECAR=<port> <token>\n``.
  Subsequent stdout lines are JSON log records (structlog
  ``JSONRenderer``); the Rust spawn parser consumes the first line
  only and forwards the rest to its tracing layer (G-14).
"""

from __future__ import annotations

import secrets
import socket
import sys

from fastapi import FastAPI
import uvicorn

from guardiabox.config import Settings, get_settings
from guardiabox.logging import configure as configure_logging, get_logger
from guardiabox.ui.tauri.sidecar.app import create_app

__all__ = ["main"]

_HANDSHAKE_PREFIX = "GUARDIABOX_SIDECAR"
"""Prefix the Rust shell scans for on the first stdout line."""

_TOKEN_BYTES = 32
"""Random octets fed into ``secrets.token_urlsafe`` (becomes ~43 chars b64)."""


def _generate_session_token() -> str:
    """Return a fresh URL-safe token of at least 256 bits of entropy."""
    return secrets.token_urlsafe(_TOKEN_BYTES)


def _pick_free_port(host: str) -> int:
    """Bind a transient socket to ``host:0`` and let the OS assign a port.

    The kernel guarantees the returned port is currently free; a tiny
    race window exists between the close and uvicorn's bind, but the
    sidecar runs alone on loopback, so the practical collision rate is
    negligible. If uvicorn does fail to bind, the parent process
    notices the missing handshake line and retries -- documented as a
    follow-up resilience improvement (out of MVP scope).
    """
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((host, 0))
        port: int = s.getsockname()[1]
    return port


def _print_handshake(*, port: int, token: str) -> None:
    """Emit the single-line handshake on stdout, then flush.

    The Rust shell reads exactly one newline-terminated line from the
    child's stdout to recover ``(port, token)``. Flushing is required
    because the handshake is the very first byte the shell expects --
    a buffered write would deadlock the spawn handshake.
    """
    sys.stdout.write(f"{_HANDSHAKE_PREFIX}={port} {token}\n")
    sys.stdout.flush()


def _build_uvicorn_config(
    *,
    app: FastAPI,
    host: str,
    port: int,
    log_level: str,
) -> uvicorn.Config:
    """Assemble the :class:`uvicorn.Config` for the sidecar.

    ``access_log=False`` so the access channel does not duplicate the
    structlog event stream. ``log_config=None`` keeps uvicorn from
    overriding our :mod:`guardiabox.logging` setup.
    """
    return uvicorn.Config(
        app,
        host=host,
        port=port,
        log_level=log_level.lower(),
        access_log=False,
        log_config=None,
    )


def main() -> int:
    """Sidecar entry point.

    Returns:
        Unix-style exit code: 0 on graceful shutdown, 130 on SIGINT,
        1 on unexpected exception (uvicorn server.run()).
    """
    settings: Settings = get_settings()
    configure_logging(level=settings.sidecar.log_level, json=True)
    log = get_logger("guardiabox.sidecar.main")

    session_token = _generate_session_token()
    port = (
        settings.sidecar.port
        if settings.sidecar.port != 0
        else _pick_free_port(settings.sidecar.host)
    )
    app = create_app(session_token=session_token, settings=settings)

    config = _build_uvicorn_config(
        app=app,
        host=settings.sidecar.host,
        port=port,
        log_level=settings.sidecar.log_level,
    )
    server = uvicorn.Server(config)

    # Print AFTER server is constructed (so any config error blows up
    # before we advertise a port that won't bind) but BEFORE
    # ``server.run()`` blocks the main thread. Uvicorn installs its own
    # SIGINT/SIGTERM handlers when ``server.run()`` enters its asyncio
    # loop -- we deliberately do not wrap them.
    log.info(
        "sidecar.handshake",
        host=settings.sidecar.host,
        port=port,
        # session_token NEVER logged: structlog's _redact_secrets
        # processor scrubs it, but we don't even include it here.
    )
    _print_handshake(port=port, token=session_token)

    try:
        server.run()
    except KeyboardInterrupt:
        log.info("sidecar.sigint")
        return 130
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
